### ISSUE TITLE
Handling & Pace Impact in lap-time formula

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#80]
The Handling and Pace figures I add in don't seem to be doing much?  I just re-ran the race by making sure that Ferrari had the LOWEST possible numbers (as in 0.1 for each), while Porsche had the HIGHEST possible (as in 9.9 for each) and it has only meant a couple of seconds difference across a 100 lap race.  I expected that would make a far bigger impact tbh...particularly with Ferrari having the top car for this track too, yet they don't even win the race?

That's the biggest issue about the race result...the pace of the teams that should be near the top seems to be heavily diluted - can we tweak that formula please to make those totals have more of an impact?

**Comment by christopherh0rn** [comment]
I'm afraid you'll have to be much more specific about what you want before I can adjust this I'm afraid.

Current formulae are:
```team handling = ((6 - (team chassis / 5) - (team gearbox / 10)) + convertedSetUpDifference) * track handling importance```

```team pace = (( 6 - (team engine / 5) - (team gearbox / 10)) + convertedSetUpDifference) * track pace importance```

**Comment by JonBeagles** [comment]
ConvertedSetUpDifference is the difference between the ideal and actual car part setups...so that's the number I want to enhance. Can we have just that number *5 please?

It was only worth a tiny amount previously, so keen for that to be more prevalent for future tracks.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
So for clarity you'd like those formula changing to:

`team handling = ((6 - (team chassis / 5) - (team gearbox / 10)) + (convertedSetUpDifference * 5)) * track handling importance`

`team pace = (( 6 - (team engine / 5) - (team gearbox / 10)) + (convertedSetUpDifference * 5)) * track pace importance`

**Comment by JonBeagles** [comment]
Yes - if you can implement that whenever is convenient this week, I will re-run the Indy race to just check that *5 doesn't make it totally nonsense!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
As this is such a tiny change I'm happy to make this without any extra charge. Would you like both qualifying and the race to have this change or just the race?

**Comment by JonBeagles** [comment]
Both please mate :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
This is now on staging. If you could run your test race there (the DB is currently identical to live) that would be great. Just to save us merging this into the main branch if it is not correct.

Just to give you a flavour, in the unit tests, which use a driver who takes every corner at indy in top gear with 0 breaking, they went from 72.389 seconds for a lap to 84.997. Not a wholly realistic scenario but just thought I'd flag!

Staging is at https://staging.f1revisited.co.uk/dashboard and has the same user and pass as live.

**Comment by JonBeagles** [comment]
Not sure how to run a test race on staging mate?  There's no quali session there and it seems a lot of effort to setup a quali session on staging and get players to do a fake quali there.

Is it possible to import the Indy quali session onto staging? If not, can we just make the change live instead...

All that said, perhaps *5 is too much if it's adding that much to the time. Let's go for *3 instead if that's ok?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
Ah, it is all already on there, I just changed the end date of the
qualifying so it's not finished yet. Will adjust back when I'm home tonight.

**Comment by christopherh0rn** [comment]
To confirm, the end date has been adjusted back to a date in the past and the formulas changes to use `* 3` rather than `* 5` have been deployed to staging. For insight, this gives that unit test for Indy a lap time of 78.693s.

**Comment by JonBeagles** [comment]
Awesome thanks mate

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by JonBeagles** [comment]
Something is VERY wrong here - I deliberately made Porsche's Pace and Handling the worst possible...and they are winning the race.  That formula is working the opposite way it should...the lower the Handling and Pace the better, but it seems its down as the higher the better right now!

Good news is that the issue isn't the change you just made - that change is fine.  It's the formula with Team Pace and Handling at the core that is interpreting it incorrectly...

It must be the ConvertedSetupDifference formula...

team handling = ((6 - (team chassis / 5) - (team gearbox / 10)) + (convertedSetUpDifference * 3)) * track handling importance

That formula should mean that the lower the convertedSetUpDifference is the less time is added on.  e.g. if that figure was 0.1 for handling then it should become 0.3 that's added to the lap time...whereas if the figure was 9.9 then it should become 29.7 added on...more time added on is a bad thing.  And yet Porsche with 9.9 have increased their pace significantly...while Ferrari who I changed to 0.1 have decreased significantly.

Ergo that convertedSetUpDifference formula must be wrong - can you show me what that is please?

**Comment by christopherh0rn** [comment]
convertedSetUpDifference = totalSetUpDifference / 10

totalSetUpDifference = power + acceleration + handling

---

power = abs(idealPower - (engine - gearbox))

idealPower = track's idealEngine - track's idealGearbox

---

acceleration = abs(idealAcceleration - (gearbox - chassis))
    
idealAcceleration = track's idealGearbox - track's idealChassis

---

handling = abs(idealHandling - (chassis - engine))

idealHandling = track's idealChassis - track's idealEngine

**Comment by JonBeagles** [comment]
Good news - that all looks good.  So question then - where do the Pace and Handling figures I put in on the Teams page get factored in?  Whatever formula contains them likely needs to go from a + to a - methinks...

![image](https://user-images.githubusercontent.com/85413662/152621343-a665ec6e-9f50-404e-93b5-67b00f367920.png)

**Comment by JonBeagles** [comment]
That's Porsche's totals there FYI.

**Comment by christopherh0rn** [comment]
Aaaah, those two fields are not used anywhere and are actually legacy fields. They stem from the misunderstanding we discovered [here](https://github.com/christopherh0rn/f1-revisited-bugs/issues/70#issuecomment-942780368).

I will remove them from the settings now.

These were originally flat values but have become these two formulas:
`team handling = ((6 - (team chassis / 5) - (team gearbox / 10)) + (convertedSetUpDifference * 3)) * track handling importance`

`team pace = ((6 - (team engine / 5) - (team gearbox / 10)) + (convertedSetUpDifference * 3)) * track pace importance`

**Comment by JonBeagles** [comment]
So the question then becomes why Porsche got so fast after I changed those values to be 9.9s - they were mid-range in terms of the formula we amended, so makes no sense that they would become quickest.

Will do another test and see what happens now - interesting to see if you removing those changes things! Just hope they aren't hard-wired into the database at the previous value totals!!!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
I've pushed those changes removing those fields. They were literally being ignored everywhere so shouldn't have been having literally any effect on anything.

**Comment by JonBeagles** [comment]
Cool - will run a test when I get chance...though I'm on a plane to the States right now so might take a little while before I can! :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by JonBeagles** [comment]
So you were right, removing those fields seemingly does nothing.

HOWEVER, Porsche are currently claiming a 1-2-3-5 (over 2 minutes ahead of most other teams), with a car that is frankly very very average.  Their strategy is similar to others and I cannot believe that they would have got fuel so perfect and all other teams didn't.  That leaves 2 possibilities - a problem with the team pace/handling formulae or they are running incredibly high risks and that's making the difference.

As such, can you show me the breakdown for the following drivers on Lap 100 for the most recent race I ran:

Willy Mairesse (Porsche)
Keith Greene (Ferrari)

NB - both Porsche and Ferrari are running the same tyres (Dunlop), while there is a different with brakes, both have a value of 2 in the dry.  So only fuel, risks and pace/handling calculations remain.  I am massively leaning towards the issue being within the pace/handling calculations so in anticipation of that, if you could break down those calculations in the comparison that would be ideal.

**Comment by JonBeagles** [comment]
Or 1 other possiility I just realised is Race Setup...which is a totally legitimate reason to be quicker.  Running those numbers now, so that will give a heads up if Porsche did have the best setups...

**Comment by JonBeagles** [comment]
Ah and it all becomes clear...top setups are for the top people in the race.  Just a coincidence that the Porsche team all have great setups.  So no need to show the comparison - I'm comfortable the latest result is correct.  Although the team impact still isn't quite enough for my liking - so let's take that to *5 in that formula again (the one we just had at *3) and that should suffice with this element :)

**Comment by christopherh0rn** [comment]
Team impact is reverted to *5 in those formulas again.
